# 工作流程的名稱
name: CI Demo

# 觸發工作流程的事件
on:
  # 當程式碼被推送到 main 分支時觸發
  push:
    branches: ["main"]
  # 當有 Pull Request 到 main 分支時觸發
  pull_request:
    branches: ["main"]
  workflow_dispatch:

# 工作流程中的工作
jobs:
  analyze:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com/${{ steps.coverage.outputs.report }}
    steps:
      - name: 分析代碼覆蓋率
        id: coverage
        run: |
          # 假設這是我們的分析結果
          echo "report=hello.html" >> $GITHUB_OUTPUT
